on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0'


permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
            tag: v${{github.event.inputs.version}}
            name: test v${{github.event.inputs.version}} released!
            bodyFile: ./release_notes.cmd
