on:
  push:
    branches:
    - main

jobs:
  create-releaseNotes:
    name: addEntry to releaseNotes
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          ref: main
          fetch-depth: 0

    - name: Config git
      run: |
        git config --global user.email "bala.bhuvan.varma.uppalapu@intel.com"
        git config --global user.name "buppalapSrr"
    - name: Create branch name and PR body
      run: |
        echo "Entered 2nd step"
        DATE="$(date +%Y-%m-%d)"
        BRANCH_NAME="releaseNotes/$DATE"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        {
           echo "PR_BODY<<EOF"
           echo "Adding an entry to release notes."
           echo "pr - ${{  github.event.head_commit.url }}"
           echo "EOF"
        } >> $GITHUB_ENV
        echo "Branch name is $BRANCH_NAME"
    - name: Create a branch for adding entry to release notes
      run: |
        git branch -D $BRANCH_NAME &> /dev/null || true
        git checkout -b $BRANCH_NAME -t origin/main
        echo "Branch Created it is $BRANCH_NAME"
        
    - name: Add the entry to Release
      env:
        AUTHOR: ${{ github.event.head_commit.author.name }}
        MESSAGE: ${{ github.event.head_commit.message }}
        URL: ${{  github.event.head_commit.url }}

      run: |
        if [ -f ./ReleaseNotes.txt ]; then
          echo "#Release Notes" > ./ReleaseNotes.txt
        fi
        echo "-----------------" >> ./ReleaseNotes.txt
        echo "###Author -  $AUTHOR" >> ./ReleaseNotes.txt
        echo "###CommitMessage - $MESSAGE" >> ./ReleaseNotes.txt
        echo "###Link to Commit - $URL" >> ./ReleaseNotes.txt
        cat ./ReleaseNotes.txt

    - name: Commit the changes in ReleaseNotes.md
      run: |
        git add .
        git commit \
        -m "[auto branch merge] Added entry to release notes ${{  github.sha }}" \
        -m "$PR_BODY"
        git remote set-url origin https://${{ secrets.IGCBOT_TOKEN }}@github.com/buppalapSrr/TestingReleaseNotes.git
        git push origin $BRANCH_NAME 
